export const AreaCodes = [
    { label: "Algeria ", code: "+213" , uniCode: "gh"},
    { label: "Andorra ", code: "+376" , uniCode: "gh"},
    { label: "Angola ", code: "+244" , uniCode: "gh"},
    { label: "Anguilla ", code: "+1264" , uniCode: "gh"},
    { label: "Antigua & Barbuda ", code: "+1268" , uniCode: "gh"},
    { label: "Argentina ", code: "+54" , uniCode: "gh"},
    { label: "Armenia ", code: "+374" , uniCode: "gh"},
    { label: "Aruba ", code: "+297" , uniCode: "gh"},
    { label: "Australia ", code: "+61" , uniCode: "gh"},
    { label: "Austria ", code: "+43" , uniCode: "gh"},
    { label: "Azerbaijan ", code: "+994" , uniCode: "gh"},
    { label: "Bahamas ", code: "+1242" , uniCode: "gh"},
    { label: "Bahrain ", code: "+973" , uniCode: "gh"},
    { label: "Bangladesh ", code: "+880" , uniCode: "gh"},
    { label: "Barbados ", code: "+1246" , uniCode: "gh"},
    { label: "Belarus ", code: "+375" , uniCode: "gh"},
    { label: "Belgium ", code: "+32" , uniCode: "gh"},
    { label: "Belize ", code: "+501" , uniCode: "gh"},
    { label: "Benin ", code: "+229" , uniCode: "gh"},
    { label: "Bermuda ", code: "+1441" , uniCode: "gh"},
    { label: "Bhutan ", code: "+975" , uniCode: "gh"},
    { label: "Bolivia ", code: "+591" , uniCode: "gh"},
    { label: "Botswana ", code: "+267" , uniCode: "gh"},
    { label: "Brazil ", code: "+55" , uniCode: "gh"},
    { label: "Brunei ", code: "+673" , uniCode: "gh"},
    { label: "Bulgaria ", code: "+359" , uniCode: "gh"},
    { label: "Burkina Faso ", code: "+226" , uniCode: "gh"},
    { label: "Burundi ", code: "+257" , uniCode: "gh"},
    { label: "Cambodia ", code: "+855" , uniCode: "gh"},
    { label: "Cameroon ", code: "+237" , uniCode: "gh"},
    { label: "Canada ", code: "+1" , uniCode: "gh"},
    { label: "Cape Verde Islands ", code: "+238" , uniCode: "gh"},
    { label: "Cayman Islands ", code: "+1345" , uniCode: "gh"},
    { label: "Central African Republic ", code: "+236" , uniCode: "gh"},
    { label: "Chile ", code: "+56" , uniCode: "gh"},
    { label: "China ", code: "+86" , uniCode: "gh"},
    { label: "Colombia ", code: "+57" , uniCode: "gh"},
    { label: "Comoros ", code: "+269" , uniCode: "gh"},
    { label: "Congo ", code: "+242" , uniCode: "gh"},
    { label: "Cook Islands ", code: "+682" , uniCode: "gh"},
    { label: "Costa Rica ", code: "+506" , uniCode: "gh"},
    { label: "Croatia ", code: "+385" , uniCode: "gh"},
    { label: "Cuba ", code: "+53" , uniCode: "gh"},
    { label: "Cyprus North ", code: "+90392" , uniCode: "gh"},
    { label: "Cyprus South ", code: "+357" , uniCode: "gh"},
    { label: "Czech Republic ", code: "+42" , uniCode: "gh"},
    { label: "Denmark ", code: "+45" , uniCode: "gh"},
    { label: "Djibouti ", code: "+253" , uniCode: "gh"},
    { label: "Dominica ", code: "+1809" , uniCode: "gh"},
    { label: "Ecuador ", code: "+593" , uniCode: "gh"},
    { label: "Egypt ", code: "+20" , uniCode: "gh"},
    { label: "El Salvador ", code: "+503" , uniCode: "gh"},
    { label: "Equatorial Guinea ", code: "+240" , uniCode: "gh"},
    { label: "Eritrea ", code: "+291" , uniCode: "gh"},
    { label: "Estonia ", code: "+372" , uniCode: "gh"},
    { label: "Ethiopia ", code: "+251" , uniCode: "gh"},
    { label: "Falkland Islands ", code: "+500" , uniCode: "gh"},
    { label: "Faroe Islands ", code: "+298" , uniCode: "gh"},
    { label: "Fiji ", code: "+679" , uniCode: "gh"},
    { label: "Finland ", code: "+358" , uniCode: "gh"},
    { label: "France ", code: "+33" , uniCode: "gh"},
    { label: "French Guiana ", code: "+594" , uniCode: "gh"},
    { label: "French Polynesia ", code: "+689" , uniCode: "gh"},
    { label: "Gabon ", code: "+241" , uniCode: "gh"},
    { label: "Gambia ", code: "+220" , uniCode: "gh"},
    { label: "Georgia ", code: "+7880" , uniCode: "gh"},
    { label: "Germany ", code: "+49" , uniCode: "gh"},
    { label: "Ghana ", code: "+233" , uniCode: "gh"},
    { label: "Gibraltar ", code: "+350" , uniCode: "gh"},
    { label: "Greece ", code: "+30" , uniCode: "gh"},
    { label: "Greenland ", code: "+299" , uniCode: "gh"},
    { label: "Grenada ", code: "+1473" , uniCode: "gh"},
    { label: "Guadeloupe ", code: "+590" , uniCode: "gh"},
    { label: "Guam ", code: "+671" , uniCode: "gh"},
    { label: "Guatemala ", code: "+502" , uniCode: "gh"},
    { label: "Guinea ", code: "+224" , uniCode: "gh"},
    { label: "Guinea - Bissau ", code: "+245" , uniCode: "gh"},
    { label: "Guyana ", code: "+592" , uniCode: "gh"},
    { label: "Haiti ", code: "+509" , uniCode: "gh"},
    { label: "Honduras ", code: "+504" , uniCode: "gh"},
    { label: "Hong Kong ", code: "+852" , uniCode: "gh"},
    { label: "Hungary ", code: "+36" , uniCode: "gh"},
    { label: "Iceland ", code: "+354" , uniCode: "gh"},
    { label: "India ", code: "+91" , uniCode: "gh"},
    { label: "Indonesia ", code: "+62" , uniCode: "gh"},
    { label: "Iran ", code: "+98" , uniCode: "gh"},
    { label: "Iraq ", code: "+964" , uniCode: "gh"},
    { label: "Ireland ", code: "+353" , uniCode: "gh"},
    { label: "Israel ", code: "+972" , uniCode: "gh"},
    { label: "Italy ", code: "+39" , uniCode: "gh"},
    { label: "Jamaica ", code: "+1876" , uniCode: "gh"},
    { label: "Japan ", code: "+81" , uniCode: "gh"},
    { label: "Jordan ", code: "+962" , uniCode: "gh"},
    { label: "Kazakhstan ", code: "+7" , uniCode: "gh"},
    { label: "Kenya ", code: "+254" , uniCode: "gh"},
    { label: "Kiribati ", code: "+686" , uniCode: "gh"},
    { label: "Korea North ", code: "+850" , uniCode: "gh"},
    { label: "Korea South ", code: "+82" , uniCode: "gh"},
    { label: "Kuwait ", code: "+965" , uniCode: "gh"},
    { label: "Kyrgyzstan ", code: "+996" , uniCode: "gh"},
    { label: "Laos ", code: "+856" , uniCode: "gh"},
    { label: "Latvia ", code: "+371" , uniCode: "gh"},
    { label: "Lebanon ", code: "+961" , uniCode: "gh"},
    { label: "Lesotho ", code: "+266" , uniCode: "gh"},
    { label: "Liberia ", code: "+231" , uniCode: "gh"},
    { label: "Libya ", code: "+218" , uniCode: "gh"},
    { label: "Liechtenstein ", code: "+417" , uniCode: "gh"},
    { label: "Lithuania ", code: "+370" , uniCode: "gh"},
    { label: "Luxembourg ", code: "+352" , uniCode: "gh"},
    { label: "Macao ", code: "+853" , uniCode: "gh"},
    { label: "Macedonia ", code: "+389" , uniCode: "gh"},
    { label: "Madagascar ", code: "+261" , uniCode: "gh"},
    { label: "Malawi ", code: "+265" , uniCode: "gh"},
    { label: "Malaysia ", code: "+60" , uniCode: "gh"},
    { label: "Maldives ", code: "+960" , uniCode: "gh"},
    { label: "Mali ", code: "+223" , uniCode: "gh"},
    { label: "Malta ", code: "+356" , uniCode: "gh"},
    { label: "Marshall Islands ", code: "+692" , uniCode: "gh"},
    { label: "Martinique ", code: "+596" , uniCode: "gh"},
    { label: "Mauritania ", code: "+222" , uniCode: "gh"},
    { label: "Mayotte ", code: "+269" , uniCode: "gh"},
    { label: "Mexico ", code: "+52" , uniCode: "gh"},
    { label: "Micronesia ", code: "+691" , uniCode: "gh"},
    { label: "Moldova ", code: "+373" , uniCode: "gh"},
    { label: "Monaco ", code: "+377" , uniCode: "gh"},
    { label: "Mongolia ", code: "+976" , uniCode: "gh"},
    { label: "Montserrat ", code: "+1664" , uniCode: "gh"},
    { label: "Morocco ", code: "+212" , uniCode: "gh"},
    { label: "Mozambique ", code: "+258" , uniCode: "gh"},
    { label: "Myanmar ", code: "+95" , uniCode: "gh"},
    { label: "Namibia ", code: "+264" , uniCode: "gh"},
    { label: "Nauru ", code: "+674" , uniCode: "gh"},
    { label: "Nepal ", code: "+977" , uniCode: "gh"},
    { label: "Netherlands ", code: "+31" , uniCode: "gh"},
    { label: "New Caledonia ", code: "+687" , uniCode: "gh"},
    { label: "New Zealand ", code: "+64" , uniCode: "gh"},
    { label: "Nicaragua ", code: "+505" , uniCode: "gh"},
    { label: "Niger ", code: "+227" , uniCode: "gh"},
    { label: "Nigeria ", code: "+234" , uniCode: "gh"},
    { label: "Niue ", code: "+683" , uniCode: "gh"},
    { label: "Norfolk Islands ", code: "+672" , uniCode: "gh"},
    { label: "Northern Marianas ", code: "+670" , uniCode: "gh"},
    { label: "Norway ", code: "+47" , uniCode: "gh"},
    { label: "Oman ", code: "+968" , uniCode: "gh"},
    { label: "Palau ", code: "+680" , uniCode: "gh"},
    { label: "Panama ", code: "+507" , uniCode: "gh"},
    { label: "Papua New Guinea ", code: "+675" , uniCode: "gh"},
    { label: "Paraguay ", code: "+595" , uniCode: "gh"},
    { label: "Peru ", code: "+51" , uniCode: "gh"},
    { label: "Philippines ", code: "+63" , uniCode: "gh"},
    { label: "Poland ", code: "+48" , uniCode: "gh"},
    { label: "Portugal ", code: "+351" , uniCode: "gh"},
    { label: "Puerto Rico ", code: "+1787" , uniCode: "gh"},
    { label: "Qatar ", code: "+974" , uniCode: "gh"},
    { label: "Reunion ", code: "+262" , uniCode: "gh"},
    { label: "Romania ", code: "+40" , uniCode: "gh"},
    { label: "Russia ", code: "+7" , uniCode: "gh"},
    { label: "Rwanda ", code: "+250" , uniCode: "gh"},
    { label: "San Marino ", code: "+378" , uniCode: "gh"},
    { label: "Sao Tome & Principe ", code: "+239" , uniCode: "gh"},
    { label: "Saudi Arabia ", code: "+966" , uniCode: "gh"},
    { label: "Senegal ", code: "+221" , uniCode: "gh"},
    { label: "Serbia ", code: "+381" , uniCode: "gh"},
    { label: "Seychelles ", code: "+248" , uniCode: "gh"},
    { label: "Sierra Leone ", code: "+232" , uniCode: "gh"},
    { label: "Singapore ", code: "+65" , uniCode: "gh"},
    { label: "Slovak Republic ", code: "+421" , uniCode: "gh"},
    { label: "Slovenia ", code: "+386" , uniCode: "gh"},
    { label: "Solomon Islands ", code: "+677" , uniCode: "gh"},
    { label: "Somalia ", code: "+252" , uniCode: "gh"},
    { label: "South Africa ", code: "+27" , uniCode: "gh"},
    { label: "Spain ", code: "+34" , uniCode: "gh"},
    { label: "Sri Lanka ", code: "+94" , uniCode: "gh"},
    { label: "St. Helena ", code: "+290" , uniCode: "gh"},
    { label: "St. Kitts ", code: "+1869" , uniCode: "gh"},
    { label: "St. Lucia ", code: "+1758" , uniCode: "gh"},
    { label: "Sudan ", code: "+249" , uniCode: "gh"},
    { label: "Suriname ", code: "+597" , uniCode: "gh"},
    { label: "Swaziland ", code: "+268" , uniCode: "gh"},
    { label: "Sweden ", code: "+46" , uniCode: "gh"},
    { label: "Switzerland ", code: "+41" , uniCode: "gh"},
    { label: "Syria ", code: "+963" , uniCode: "gh"},
    { label: "Taiwan ", code: "+886" , uniCode: "gh"},
    { label: "Tajikstan ", code: "+7" , uniCode: "gh"},
    { label: "Thailand ", code: "+66" , uniCode: "gh"},
    { label: "Togo ", code: "+228" , uniCode: "gh"},
    { label: "Tonga ", code: "+676" , uniCode: "gh"},
    { label: "Trinidad & Tobago ", code: "+1868" , uniCode: "gh"},
    { label: "Tunisia ", code: "+216" , uniCode: "gh"},
    { label: "Turkey ", code: "+90" , uniCode: "gh"},
    { label: "Turkmenistan ", code: "+7" , uniCode: "gh"},
    { label: "Turks & Caicos Islands ", code: "+1649" , uniCode: "gh"},
    { label: "Tuvalu ", code: "+688" , uniCode: "gh"},
    { label: "Uganda ", code: "+256" , uniCode: "gh"},
    { label: "Ukraine ", code: "+380" , uniCode: "gh"},
    { label: "United Arab Emirates ", code: "+971" , uniCode: "gh"},
    { label: "United States", code: "+1" , uniCode: "us"},
    { label: "Uruguay ", code: "+598" , uniCode: "gh"},
    { label: "Uzbekistan ", code: "+7" , uniCode: "gh"},
    { label: "Vanuatu ", code: "+678" , uniCode: "gh"},
    { label: "Vatican City ", code: "+379" , uniCode: "gh"},
    { label: "Venezuela ", code: "+58" , uniCode: "gh"},
    { label: "Vietnam ", code: "+84" , uniCode: "gh"},
    { label: "Virgin Islands - British ", code: "+1284" , uniCode: "gh"},
    { label: "Virgin Islands - US ", code: "+1340" , uniCode: "gh"},
    { label: "Wallis & Futuna ", code: "+681" , uniCode: "gh"},
    { label: "Yemen (North)", code: "+969" , uniCode: "gh"},
    { label: "Yemen (South)", code: "+967" , uniCode: "gh"},
    { label: "Zambia ", code: "+260" , uniCode: "gh"},
    { label: "Zimbabwe ", code: "+263" , uniCode: "gh"},
]